YUI.add("yuidoc-meta", function(Y) {
   Y.YUIDoc = { meta: {
    "classes": [
        "Restypie.API",
        "Restypie.BasicRoutes",
        "Restypie.BasicRoutes.DeleteSingleRoute",
        "Restypie.BasicRoutes.GetManyRoute",
        "Restypie.BasicRoutes.GetSingleRoute",
        "Restypie.BasicRoutes.OptionsRoute",
        "Restypie.BasicRoutes.PatchSingleRoute",
        "Restypie.BasicRoutes.PostRoute",
        "Restypie.BasicRoutes.PutSingleRoute",
        "Restypie.Bundle",
        "Restypie.Codes",
        "Restypie.Fields",
        "Restypie.Fields.AbstractField",
        "Restypie.Fields.AbstractNumberField",
        "Restypie.Fields.AbstractRelationField",
        "Restypie.Fields.AnyField",
        "Restypie.Fields.BooleanField",
        "Restypie.Fields.DateField",
        "Restypie.Fields.FileField",
        "Restypie.Fields.FloatField",
        "Restypie.Fields.IntegerField",
        "Restypie.Fields.StringField",
        "Restypie.Fields.ToManyField",
        "Restypie.Fields.ToOneField",
        "Restypie.Methods",
        "Restypie.Operators",
        "Restypie.Operators.AbstractListOperator",
        "Restypie.Operators.AbstractOperator",
        "Restypie.Operators.Eq",
        "Restypie.Operators.Gt",
        "Restypie.Operators.Gte",
        "Restypie.Operators.In",
        "Restypie.Operators.Lt",
        "Restypie.Operators.Lte",
        "Restypie.Operators.Ne",
        "Restypie.Operators.Nin",
        "Restypie.Resources",
        "Restypie.Resources.AbstractResource",
        "Restypie.Resources.FixturesResource",
        "Restypie.Resources.ProxyResource",
        "Restypie.Resources.SequelizeResource",
        "Restypie.RestErrors",
        "Restypie.RestErrors.AbstractRestError",
        "Restypie.RestErrors.BadRequest",
        "Restypie.RestErrors.Forbidden",
        "Restypie.RestErrors.InternalServerError",
        "Restypie.RestErrors.NotAcceptable",
        "Restypie.RestErrors.NotFound",
        "Restypie.RestErrors.NotImplemented",
        "Restypie.RestErrors.Unauthorized",
        "Restypie.RestErrors.UnsupportedMediaType",
        "Restypie.Route",
        "Restypie.RoutesSorter",
        "Restypie.Serializers",
        "Restypie.Serializers.AbstractSerializer",
        "Restypie.Serializers.JSONSerializer",
        "Restypie.TemplateErrors",
        "Restypie.Url",
        "Restypie.Utils"
    ],
    "modules": [],
    "allModules": [],
    "elements": []
} };
});